### ISSUE TITLE
Empty alt attribute treated the same as a missing one

### ISSUE THREAD

**Issue by philwolstenholme** [ckundo/n-alt#2]
I might be wrong, but does the plugin treat `alt=""` the same as no `alt` attribute at all?

I think the plugin should treat them differently, as empty `alt` attributes are allowed for purely decorative images: https://www.w3.org/WAI/tutorials/images/decorative/

**Comment by ckundo** [comment]
Thanks @philwolstenholme, I've solicited opinions on this from blind users on this. If this were a validation or compliance plugin, you'd be absolutely correct. It's not though, and from what I can tell, content creators are way too liberal with `alt=""`. Open to more discussion, especially want opinions from screen reader users. See https://twitter.com/ckundo/status/1262442909649027078 and https://tink.uk/text-descriptions-emotion-rich-images/

**Comment by philwolstenholme** [comment]
Ah, gotcha! I'm sure you're right about `alt=""` being an easy way out for many!
